# Generated by Django 5.2.14 on 2026-05-27 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('mens', "Men's Wear"), ('womens', "Women's Clothing"), ('kente', 'Kente & Traditional'), ('fabric', 'Fabrics & Textiles'), ('accessories', 'Accessories'), ('wholesale', 'Wholesale Lots'), ('traditional', 'Traditional Wear'), ('smock', 'Smock & Fugu')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Max price Avefon pays', max_digits=10)),
                ('unit', models.CharField(default='piece', max_length=30)),
                ('min_qty', models.PositiveIntegerField(default=1)),
                ('badge', models.CharField(blank=True, choices=[('', 'None'), ('URGENT', '🔥 Urgent'), ('HOT', '⭐ Hot'), ('NEW', '✨ New')], default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('pct_filled', models.PositiveIntegerField(default=0, help_text='% of stock filled (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-badge', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SellerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(editable=False, max_length=20, unique=True)),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_phone', models.CharField(max_length=20)),
                ('seller_email', models.EmailField(blank=True, max_length=254)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(default='Brand New', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending Review'), ('approved', '✅ Approved'), ('received', '📦 Goods Received'), ('paid', '💰 Paid'), ('rejected', '❌ Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='backend.buyingitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
