# Generated by Django 5.2.14 on 2026-05-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buying_items/'),
        ),
        migrations.AddField(
            model_name='selleroffer',
            name='location',
            field=models.CharField(blank=True, help_text='Seller location/address for delivery', max_length=200),
        ),
    ]
